app = "x73-database"
primary_region = "arn"

image = "postgres:15"

[env]
  POSTGRES_USER = "agust"
  POSTGRES_PASSWORD = "0384ngiosbndfk_3rnisd%23nfi_windsbr3n"
  POSTGRES_DB = "x73-db"

[mounts]
  source = "pgdata"
  destination = "/var/lib/postgresql/data"

[[services]]
  internal_port = 5432
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1
